# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                admin:
                  password: $2y$13$oM5t3SHkr3bgfKhB8pw3RuGJspXA38CUe75zbJZSsChAwtAuLXLyi
                  roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: in_memory
            form_login:
              login_path: login
              check_path: login
            logout: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
